#
# Continuous integration settings for Travis CI
#
dist: xenial
os: linux
branches:
  only:
    - master

# Python TravisCI settings
# See: https://docs.travis-ci.com/user/languages/python/ for more information.
language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r dev-requirements.txt

# Build Stages Order
stages:
  - pylint
  - test

# command to run tests
script: pytest

# Build Stages
# If caching errors occur, please clear the cache on the Travis CI website.
jobs:
  include:
    # This stage makes sure that our Python code styles are the same.
    - stage: pylint
      script:
        - pylint app/
    # This stage runs the Python tests using Python 3.6.
    - stage: test
      python: "3.6"
      script:
        - python manage.py makemigrations app
        - python manage.py migrate
        - python manage.py test app
    # This stage runs the Python tests using Python 3.7.
    - stage: test
      python: "3.7"
      script:
        - python manage.py makemigrations app
        - python manage.py migrate
        - python manage.py test app
    # This stage runs the Python tests using Python 3.8.
    - stage: test
      python: "3.8"
      script:
        - python manage.py makemigrations app
        - python manage.py migrate
        - python manage.py test app

# Cache
cache:
  pip: true
  directories:
    - $HOME/download-cache
